import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Refund Policy | rbptech",
  description: "Review our refund policy for digital services and AI generations.",
};

export default function RefundPolicyPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-12">
      <div className="space-y-4">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-brand-deep">
          Refund <span className="text-brand-indigo glow-text-brand">Policy</span>
        </h1>
        <p className="text-brand-navy/70 text-sm">Last updated: June 2026</p>
      </div>

      <div className="prose prose-sm prose-slate max-w-none text-brand-navy/80 space-y-8">
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">1. General Refund Policy</h2>
          <p>
            Due to the heavy computational GPU costs associated with generating AI-tailored documents, and the non-returnable nature of digital intellectual output, <strong>all purchases made on rbptech are generally non-refundable.</strong>
          </p>
          <p>
            By purchasing credits or generating a document, you acknowledge that you are receiving a digital service that is consumed at the moment of generation.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">2. Technical Failures and Exceptions</h2>
          <p>
            We stand behind the technical reliability of our platform. We will grant refunds or credit reimbursements in the following specific scenarios:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Failed Generation:</strong> If a system error, API timeout, or critical bug causes the AI generation to fail completely and your credits were deducted, we will refund the specific credits used or issue a refund for the transaction.</li>
            <li><strong>Blank Outputs:</strong> If the final compiled PDF document is entirely blank or corrupted due to our compiler failing.</li>
            <li><strong>Duplicate Charges:</strong> If a payment processing error results in you being charged multiple times for a single transaction.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">3. Non-Refundable Scenarios</h2>
          <p>
            Refunds will <strong>not</strong> be issued for:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Stylistic Dissatisfaction:</strong> Dissatisfaction with the specific phrasing, tone, or stylistic choices generated by the AI. You have access to the built-in Editor to manually tweak and modify the output to your exact preferences before finalizing it.</li>
            <li><strong>Job Application Outcomes:</strong> We do not guarantee interviews or job placements. Lack of success in your job search does not constitute grounds for a refund.</li>
            <li><strong>Unused Credits:</strong> Account credits that remain unused are non-refundable and will remain in your account for future use.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">4. Requesting a Refund</h2>
          <p>
            If you believe you qualify for a refund based on a technical failure, please contact our support team within <strong>7 days</strong> of the incident. Please include your account email address, the date of the transaction, and any error messages you received.
          </p>
          <p>
            Approved refunds will be processed within 5-10 business days and will be credited back to your original payment method via PayFast.
          </p>
        </section>
      </div>
    </div>
  );
}
