import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | rbptech",
  description: "Review the terms and conditions governing the use of rbptech's AI resume tailoring compiler and pay-as-you-go services.",
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-12">
      <div className="space-y-4">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-brand-deep">
          Terms of <span className="text-brand-indigo glow-text-brand">Service</span>
        </h1>
        <p className="text-brand-navy/70 text-sm">Last updated: June 2026</p>
      </div>

      <div className="prose prose-sm prose-slate max-w-none text-brand-navy/80 space-y-8">
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">1. Agreement to Terms and Acceptance</h2>
          <p>
            These Terms of Service ("Terms") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and rbptech ("Company", "we", "us", or "our"), concerning your access to and use of the rbptech website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the "Site"). We are registered in South Africa and operate internationally.
          </p>
          <p>
            You agree that by accessing the Site, you have read, understood, and agreed to be bound by all of these Terms of Service. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF SERVICE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY. Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms of Service at any time and for any reason. We will alert you about any changes by updating the "Last updated" date of these Terms of Service, and you waive any right to receive specific notice of each such change. Please ensure that you check the applicable Terms every time you use our Site so that you understand which Terms apply.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">2. Intellectual Property Rights and Licensing</h2>
          <p>
            Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the "Content") and the trademarks, service marks, and logos contained therein (the "Marks") are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws. The Content and the Marks are provided on the Site "AS IS" for your information and personal use only.
          </p>
          <p>
            <strong>Your Output License:</strong> You retain all ownership rights to the input data you provide (your background, resume details) and the specific output documents (PDFs, text) generated by our Services for your use. Subject to your compliance with these Terms, you are granted a worldwide, non-exclusive, royalty-free, perpetual license to use, download, modify, and distribute the tailored resumes and cover letters you generate using our Services for your personal, professional, or commercial job-seeking purposes. However, you are strictly prohibited from reselling access to the platform itself or acting as a commercial service bureau using our underlying API without explicit enterprise authorization.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">3. User Representations and Account Security</h2>
          <p>By using the Site, you represent and warrant that:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>All registration information you submit will be true, accurate, current, and complete.</li>
            <li>You will maintain the accuracy of such information and promptly update such registration information as necessary.</li>
            <li>You have the legal capacity and you agree to comply with these Terms of Service.</li>
            <li>You are not a minor in the jurisdiction in which you reside, or if a minor, you have received parental permission to use the Site.</li>
            <li>You will not access the Site through automated or non-human means, whether through a bot, script, spider, scraper, or otherwise, except as expressly permitted via our official API documentation.</li>
            <li>You will not use the Site for any illegal, unauthorized, or malicious purpose.</li>
            <li>Your use of the Site will not violate any applicable law or regulation.</li>
          </ul>
          <p>
            If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof). You are responsible for keeping your account credentials secure. We cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">4. Prohibited Activities and Acceptable Use</h2>
          <p>
            You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. As a user of the Site, you agree not to:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
            <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
            <li>Circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein.</li>
            <li>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site.</li>
            <li>Use any information obtained from the Site in order to harass, abuse, or harm another person.</li>
            <li>Make improper use of our support services or submit false reports of abuse or misconduct.</li>
            <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
            <li>Interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site.</li>
            <li>Attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site.</li>
            <li>Copy or adapt the Site’s software, including but not limited to Flash, PHP, HTML, JavaScript, TypeScript, or other code.</li>
            <li>Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">5. Purchases, Payments, and Credits</h2>
          <p>
            We operate on a pay-as-you-go credit system utilizing PayFast for payment processing. You agree to provide current, complete, and accurate purchase and account information for all purchases made via the Site. You further agree to promptly update account and payment information, including email address, payment method, and payment card expiration date, so that we can complete your transactions and contact you as needed. Sales tax will be added to the price of purchases as deemed required by us. We may change prices at any time. All payments shall be in ZAR (South African Rand) or USD depending on your locale as processed by the merchant of record.
          </p>
          <p>
            <strong>Refund Policy:</strong> Due to the heavy computational GPU costs associated with generating AI-tailored documents and the non-returnable nature of digital intellectual output, all purchases are generally non-refundable. If you experience critical technical errors that result in a wholly failed or blank document generation, please contact our support team within 7 days, and we will, at our sole discretion, refund or credit your account for the specific transaction that failed. Dissatisfaction with the stylistic choices or specific wordings generated by the AI does not constitute grounds for a refund, as you have access to the Editor to modify the final output.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">6. AI Processing, Generation Risks, and Accuracy</h2>
          <p>
            rbptech uses advanced artificial intelligence algorithms and large language models (LLMs) to tailor resumes and cover letters. While we strive for absolute accuracy and semantic alignment with your original input and the target job description, AI systems are probabilistic and non-deterministic by nature. 
          </p>
          <p>
            You explicitly acknowledge and agree that:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Verification Obligation:</strong> You are solely and ultimately responsible for reviewing, fact-checking, and verifying the absolute accuracy of any documents generated by the Service before submitting them to employers.</li>
            <li><strong>No Guarantee of Employment:</strong> We do not guarantee, represent, or warrant that using our service will result in job interviews, job offers, or any specific hiring outcomes.</li>
            <li><strong>Hallucinations and Fabrications:</strong> We are not liable for any misrepresentations, factual inaccuracies, overstatements, or "hallucinations" generated by the AI that you fail to correct prior to use. It is your responsibility to ensure the generated documents truthfully represent your actual skills, experience, and qualifications.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">7. User Generated Contributions</h2>
          <p>
            The Site may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions").
          </p>
          <p>
            By posting Contributions to any part of the Site, you automatically grant, and you represent and warrant that you have the right to grant, to us an unrestricted, unlimited, irrevocable, perpetual, non-exclusive, transferable, royalty-free, fully-paid, worldwide right, and license to host, use, copy, reproduce, disclose, sell, resell, publish, broadcast, retitle, archive, store, cache, publicly perform, publicly display, reformat, translate, transmit, excerpt (in whole or in part), and distribute such Contributions for any purpose, commercial, advertising, or otherwise, and to prepare derivative works of, or incorporate into other works, such Contributions, and grant and authorize sublicenses of the foregoing.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">8. Third-Party Websites and Content</h2>
          <p>
            The Site may contain (or you may be sent via the Site) links to other websites ("Third-Party Websites") as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software, and other content or items belonging to or originating from third parties ("Third-Party Content"). Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Site or any Third-Party Content posted on, available through, or installed from the Site. Inclusion of, linking to, or permitting the use or installation of any Third-Party Websites or any Third-Party Content does not imply approval or endorsement thereof by us.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">9. Site Management and Termination</h2>
          <p>
            We reserve the right, but not the obligation, to: (1) monitor the Site for violations of these Terms of Service; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms of Service, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Site or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Site in a manner designed to protect our rights and property and to facilitate the proper functioning of the Site.
          </p>
          <p>
            These Terms of Service shall remain in full force and effect while you use the Site. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS OF SERVICE, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SITE (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OF SERVICE OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SITE OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">10. Modifications and Interruptions</h2>
          <p>
            We reserve the right to change, modify, or remove the contents of the Site at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Site. We also reserve the right to modify or discontinue all or part of the Site without notice at any time. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Site.
          </p>
          <p>
            We cannot guarantee the Site will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Site, resulting in interruptions, delays, or errors. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Site during any downtime or discontinuance of the Site.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">11. Disclaimer of Warranties</h2>
          <p className="uppercase text-xs font-bold text-brand-navy/60 tracking-wider">
            THE SITE IS PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SITE AND OUR SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SITE AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SITE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE SITE AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">12. Limitation of Liability</h2>
          <p className="uppercase text-xs font-bold text-brand-navy/60 tracking-wider">
            IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE SIX (6) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING. CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">13. Indemnification</h2>
          <p>
            You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) your Contributions; (2) use of the Site; (3) breach of these Terms of Service; (4) any breach of your representations and warranties set forth in these Terms of Service; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the Site with whom you connected via the Site. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">14. Dispute Resolution and Governing Law</h2>
          <p>
            <strong>Informal Negotiations:</strong> To expedite resolution and control the cost of any dispute, controversy, or claim related to these Terms of Service (each "Dispute" and collectively, the "Disputes") brought by either you or us (individually, a "Party" and collectively, the "Parties"), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least thirty (30) days before initiating arbitration. Such informal negotiations commence upon written notice from one Party to the other Party.
          </p>
          <p>
            <strong>Binding Arbitration:</strong> If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the recognized arbitration associations in South Africa or internationally depending on jurisdiction.
          </p>
          <p>
            <strong>Governing Law:</strong> These Terms shall be governed by and defined following the laws of South Africa. rbptech and yourself irrevocably consent that the courts of South Africa shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">15. Term and Termination</h2>
          <p>
            These Terms of Service shall remain in full force and effect while you use the Site. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS OF SERVICE, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SITE (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OF SERVICE OR OF ANY APPLICABLE LAW OR REGULATION. We may terminate your use or participation in the Site or delete your account and any content or information that you posted at any time, without warning, in our sole discretion.
          </p>
          <p>
            If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">16. DMCA Notice and Takedown Policy</h2>
          <p>
            We respect the intellectual property rights of others. If you believe that any material available on or through the Site infringes upon any copyright you own or control, please immediately notify our Designated Copyright Agent using the contact information provided below (a "Notification"). A copy of your Notification will be sent to the person who posted or stored the material addressed in the Notification. Please be advised that pursuant to federal law you may be held liable for damages if you make material misrepresentations in a Notification. Thus, if you are not sure that material located on or linked to by the Site infringes your copyright, you should consider first contacting an attorney.
          </p>
          <p>
            All Notifications should meet the requirements of DMCA 17 U.S.C. § 512(c)(3) and include the following information: (1) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (2) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Site are covered by the Notification, a representative list of such works on the Site; (3) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; (4) information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an email address at which the complaining party may be contacted; (5) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (6) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">17. Class Action Waiver</h2>
          <p>
            WHERE PERMITTED UNDER THE APPLICABLE LAW, YOU AND THE COMPANY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION. Unless both you and the Company agree, no arbitrator or judge may consolidate more than one person’s claims or otherwise preside over any form of a representative or class proceeding. The arbitrator may award injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim. If a court decides that applicable law precludes enforcement of any of this paragraph’s limitations as to a particular claim for relief, then that claim (and only that claim) must be severed from the arbitration and may be brought in court.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">18. Electronic Communications, Transactions, and Signatures</h2>
          <p>
            Visiting the Site, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SITE. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">19. Export Controls and Sanctions</h2>
          <p>
            You agree to comply fully with all relevant export laws and regulations of the United States, South Africa, and other applicable jurisdictions to ensure that no information, technology, or services provided by us are exported or re-exported directly or indirectly in violation of those laws. You represent and warrant that you are not located in, under the control of, or a national or resident of any country to which the United States has embargoed goods, and you are not listed on any US Government list of prohibited or restricted parties.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">20. Beta Features and Feedback</h2>
          <p>
            From time to time, we may offer new "beta" features or tools with which our users may experiment on the Site. Such features or tools are offered solely for experimental purposes and without any warranty of any kind, and may be modified or discontinued at our sole discretion. Any feedback, comments, ideas, improvements or suggestions (collectively, "Feedback") provided by you to us with respect to the Site shall remain the sole and exclusive property of the Company. We shall be free to use, copy, modify, publish, or redistribute the Feedback for any purpose and in any way without any credit or any compensation to you.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">21. Notice to California Users</h2>
          <p>
            Under California Civil Code Section 1789.3, California users of the Site are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834, or by telephone at (800) 952-5210.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">22. API License and Usage Restrictions</h2>
          <p>
            If we grant you access to our Application Programming Interface ("API"), we grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the API solely to develop, test, and support an integration with your application. You agree not to: (a) reverse engineer, decompile, or disassemble the API; (b) defeat, avoid, bypass, remove, deactivate, or otherwise circumvent any software protection or monitoring mechanisms of the API; (c) use the API to replicate or compete with the core products or services offered by us; (d) use the API in any manner that is illegal or violates the rights of third parties; or (e) exceed any rate limits or quotas established by us in our sole discretion. We reserve the right to modify, rate-limit, or deprecate the API at any time, with or without notice.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">23. Service Level Agreement (SLA) Disclaimers</h2>
          <p>
            While we endeavor to provide high availability of the Site, we do not guarantee any specific uptime or service level metrics. The Site and the underlying AI generation systems may be unavailable during scheduled maintenance windows, emergency security patching, or due to third-party vendor outages (such as cloud hosting providers or AI API upstream providers). In the event of an outage, your sole and exclusive remedy is to wait for service restoration. We shall not be liable for any missed application deadlines, lost employment opportunities, or consequential damages resulting from system downtime.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">24. Publicity and Marketing Rights</h2>
          <p>
            By creating an account, you grant us the non-exclusive, royalty-free, worldwide right to use your name, company name (if applicable), and generalized usage statistics (such as "thousands of resumes tailored") in our marketing materials, pitch decks, website testimonials, and investor relations documents. If you provide a direct testimonial or feedback, we may attribute it to you utilizing your first name and last initial unless you explicitly request anonymity in writing.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">25. Confidentiality (For Enterprise and API Users)</h2>
          <p>
            "Confidential Information" means any non-public information disclosed by either party to the other, either directly or indirectly, in writing, orally, or by inspection of tangible objects, that is designated as "Confidential" or that reasonably should be understood to be confidential given the nature of the information. Each party agrees to maintain the confidentiality of the other party's Confidential Information with the same degree of care it uses to protect its own confidential information of a similar nature, but no less than a reasonable degree of care. This obligation shall survive termination of these Terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">26. Independent Contractor Status</h2>
          <p>
            You and rbptech are independent contractors, and nothing in these Terms creates a partnership, joint venture, agency, fiduciary, or employment relationship between the parties. You have no authority to make or accept any offers or representations on our behalf.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">27. Injunctive Relief</h2>
          <p>
            You acknowledge and agree that a breach or threatened breach of these Terms, specifically regarding our intellectual property rights or the unauthorized use of the Site/API, may cause irreparable harm to the Company for which monetary damages would not be an adequate remedy. Accordingly, in the event of such a breach or threatened breach, we shall be entitled to equitable relief, including a restraining order, an injunction, specific performance, and any other relief that may be available from any court of competent jurisdiction, without the necessity of posting a bond or other security or proving actual damages.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">28. Translation and Language Interpretation</h2>
          <p>
            These Terms of Service may have been translated if we have made them available to you on our Service. You agree that the original English text shall prevail in the case of a dispute. Any ambiguities in the interpretation of these Terms shall not be construed against the drafting party.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">29. Miscellaneous</h2>
          <p>
            These Terms of Service and any policies or operating rules posted by us on the Site or in respect to the Site constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms of Service shall not operate as a waiver of such right or provision. These Terms of Service operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control (Force Majeure). If any provision or part of a provision of these Terms of Service is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Service and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms of Service or use of the Site. You agree that these Terms of Service will not be construed against us by virtue of having drafted them.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">30. Contact Us</h2>
          <p>
            In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:
          </p>
          <p className="text-brand-navy/60 italic border-l-4 border-brand-indigo pl-4 mt-2 py-2">
            <strong>rbptech Legal Department</strong><br/>
            Email: kairosounds.01@gmail.com<br/>
            Johannesburg, Gauteng, South Africa
          </p>
        </section>
      </div>
    </div>
  );
}
