import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | rbptech",
  description: "Review the terms and conditions governing the use of rbptech's AI resume tailoring compiler and pay-as-you-go services.",
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-12">
      <div className="space-y-4">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-brand-deep">
          Terms of <span className="text-brand-indigo glow-text-brand">Service</span>
        </h1>
        <p className="text-brand-navy/70 text-sm">Last updated: October 2023</p>
      </div>

      <div className="prose prose-sm prose-slate max-w-none text-brand-navy/80 space-y-8">
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">1. Agreement to Terms</h2>
          <p>
            These Terms of Service ("Terms") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and rbptech ("Company", "we", "us", or "our"), concerning your access to and use of the rbptech website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the "Site").
          </p>
          <p>
            You agree that by accessing the Site, you have read, understood, and agreed to be bound by all of these Terms of Service. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF SERVICE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">2. Intellectual Property Rights</h2>
          <p>
            Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the "Content") and the trademarks, service marks, and logos contained therein (the "Marks") are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws.
          </p>
          <p>
            <strong>Your Output:</strong> You retain all ownership rights to the input data you provide (your background, resume details) and the specific output documents (PDFs, text) generated by our Services for your use. You are granted a worldwide, non-exclusive, royalty-free license to use, download, and distribute the documents you generate using our Services.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">3. User Representations and Acceptable Use</h2>
          <p>By using the Site, you represent and warrant that:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>All registration information you submit will be true, accurate, current, and complete.</li>
            <li>You have the legal capacity and you agree to comply with these Terms of Service.</li>
            <li>You are not a minor in the jurisdiction in which you reside.</li>
            <li>You will not access the Site through automated or non-human means, whether through a bot, script, or otherwise, except as permitted via our official API (if applicable).</li>
            <li>You will not use the Site for any illegal or unauthorized purpose.</li>
          </ul>
          <p>
            You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">4. Purchases, Payments, and Credits</h2>
          <p>
            We operate on a pay-as-you-go credit system. You agree to provide current, complete, and accurate purchase and account information for all purchases made via the Site. You further agree to promptly update account and payment information, including email address, payment method, and payment card expiration date.
          </p>
          <p>
            <strong>Refund Policy:</strong> Due to the computational costs associated with generating AI-tailored documents, all purchases are generally non-refundable. If you experience technical errors that result in a failed document generation, please contact our support team within 7 days, and we will, at our sole discretion, refund the specific credits used for that failed generation.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">5. AI Processing and Generation Risks</h2>
          <p>
            rbptech uses advanced artificial intelligence algorithms to tailor resumes and cover letters. While we strive for absolute accuracy and semantic alignment, AI systems are probabilistic by nature.
          </p>
          <p>
            You acknowledge and agree that:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>You are solely responsible for reviewing and verifying the accuracy of any documents generated by the Service before submitting them to employers.</li>
            <li>We do not guarantee that using our service will result in job interviews, offers, or any specific hiring outcomes.</li>
            <li>We are not liable for any misrepresentations, factual inaccuracies, or "hallucinations" generated by the AI that you fail to correct prior to use.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">6. Disclaimer of Warranties</h2>
          <p className="uppercase text-xs font-bold text-brand-navy/60">
            The site is provided on an as-is and as-available basis. You agree that your use of the site and our services will be at your sole risk. To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the site and your use thereof, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">7. Limitation of Liability</h2>
          <p className="uppercase text-xs font-bold text-brand-navy/60">
            In no event will we or our directors, employees, or agents be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages, including lost profit, lost revenue, loss of data, or other damages arising from your use of the site, even if we have been advised of the possibility of such damages.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">8. Dispute Resolution and Governing Law</h2>
          <p>
            These Terms shall be governed by and defined following the laws of South Africa. rbptech and yourself irrevocably consent that the courts of South Africa shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-brand-deep">9. Contact Us</h2>
          <p>
            In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:
          </p>
          <p className="text-brand-navy/60 italic">
            rbptech Legal Department<br/>
            kairosounds.01@gmail.com<br/>
            Johannesburg, Gauteng, South Africa
          </p>
        </section>
      </div>
    </div>
  );
}
